### ISSUE TITLE
Inconsistent search input rendering

### ISSUE THREAD

**Issue by nickcolley** [alphagov/manuals-frontend#183]
Issue found while visiting the Scottish Government's Device Lab

Notice how when this was reimplemented a regression was introduced somewhere. (Potentially they were done at the same time, I'm not certain 😄 )

![screen shot 2016-11-21 at 21 25 28](https://cloud.githubusercontent.com/assets/2445413/20501300/3c4b0ed2-b031-11e6-9b1c-97eae0770cf3.png)
![screen shot 2016-11-21 at 21 24 49](https://cloud.githubusercontent.com/assets/2445413/20501299/3c4a65cc-b031-11e6-828e-12a82bdad706.png)

**Comment by andysellick** [comment]
I don't think this is an issue anymore - okay to close?
<img width="360" alt="screen shot 2017-05-24 at 08 30 07" src="https://cloud.githubusercontent.com/assets/861310/26391579/41cd5b02-405b-11e7-98b3-56bfad9cf9ed.png">

**Comment by fofr** [comment]
Search box looks wrong in our screenshot @andysellick.

**Comment by andysellick** [comment]
So it does. Had confused the issue with the left alignment of the contents of the green box. Obvious now you've pointed it out - thanks!
