### ISSUE TITLE
Inconsistent guttering on smaller screens

### ISSUE THREAD

**Issue by nickcolley** [alphagov/manuals-frontend#184]
Issue found while visiting the Scottish Government's Device Lab

![image](https://cloud.githubusercontent.com/assets/2445413/20501379/9b131964-b031-11e6-9d2e-deaea68387f1.png)

Here we could make the guttering on the header consistent with the guttering of the page

**Comment by andysellick** [comment]
@nickcolley this doesn't seem to be an issue anymore, page has changed considerably - ok to close?

**Comment by nickcolley** [comment]
Hmm, I don't know of any work done but seems like it's indeed not an issue anymore...
