### ISSUE TITLE
Is this still in beta?

### ISSUE THREAD

**Issue by nickcolley** [alphagov/manuals-frontend#185]
Should this application still have a beta label?

![screen shot 2016-11-21 at 21 31 29](https://cloud.githubusercontent.com/assets/2445413/20501460/ed040e5e-b031-11e6-8a53-716a82fc5b65.png)

**Comment by andysellick** [comment]
@nickcolley is still a problem or can it be closed?

**Comment by nickcolley** [comment]
It still has the banner, I'm not aware of anyone working on it, we should probably remove it.

**Comment by h-lame** [comment]
That banner is specifically for hmrc manuals I think, which might still be considered beta - worth checking with the team that owns https://github.com/alphagov/hmrc-manuals-api

**Comment by nickcolley** [comment]
Closing old issues.
