### ISSUE TITLE
Global header bar looks odd on small viewports

### ISSUE THREAD

**Issue by nickcolley** [alphagov/manuals-frontend#186]
Issue found while visiting the Scottish Government's Device Lab

![image](https://cloud.githubusercontent.com/assets/2445413/20501577/6285f098-b032-11e6-8192-7b8ba5175368.png)

![screen shot 2016-11-21 at 21 34 01](https://cloud.githubusercontent.com/assets/2445413/20501568/5b860814-b032-11e6-93c2-18d70116422b.png)

**Comment by janeoloughlin** [comment]
we have created trello card for this on FE support board https://trello.com/c/fOALAER3

**Comment by miaallers** [comment]
Not sure how you are planning on tackling it but I’d suggest that we reduce the width of the blue title box to be aligned with the header border. This will make the design consistent with the desktop version and will require no tweaking of the nav

**Comment by nickcolley** [comment]
Here's how that'd look:

![screen shot 2017-06-07 at 10 43 03](https://user-images.githubusercontent.com/2445413/26872384-44aea740-4b6e-11e7-883a-28badc15220b.png)
![screen shot 2017-06-07 at 10 43 32](https://user-images.githubusercontent.com/2445413/26872383-44ada0fc-4b6e-11e7-938e-1929fd298c24.png)

**Comment by miaallers** [comment]
Yep — could we get the top margin between the nav border and the page title (H1) block? To match the desktop version? Attaching a mock up.
![26872384-44aea740-4b6e-11e7-883a-28badc15220b](https://user-images.githubusercontent.com/18534862/26873137-b4a593d6-4b70-11e7-883e-3a857a43b134.png)

**Comment by nickcolley** [comment]
Alternatively we could have the top bar full width on smaller screens, maximizing the amount of content we can get in? Just that we have the grid's gutter with additional padding otherwise.

**Comment by andysellick** [comment]
Elsewhere this problem has been dealt with by removing the thin blue bar at the top... https://www.gov.uk/service-manual
<img width="582" alt="screen shot 2017-06-07 at 12 16 42" src="https://user-images.githubusercontent.com/861310/26875760-34fa5cce-4b7b-11e7-8213-0036942a66f9.png">

**Comment by nickcolley** [comment]
The bar is a 'GOV.UK Publishing' thing

**Comment by miaallers** [comment]
That sounds good, didn't know that was an option.
